plugins {
    id 'java'
    id 'io.github.goooler.shadow' version '8.1.8'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.warnings = false
}

dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.2-1'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'
    compileOnly 'org.projectlombok:lombok:1.18.42'
}

shadowJar {
    dependencies {

    }
}

jar.dependsOn(shadowJar)